kind: pipeline
type: docker
name: default

steps:
  - name: restore
    image: roharx/calculator-docker
    commands:
      - dotnet restore ./Calculator/Calculator.csproj --verbosity detailed

  - name: build
    image: roharx/calculator-docker
    commands:
      - dotnet build --no-restore -c Release ./Calculator/Calculator.csproj

  - name: test
    image: roharx/calculator-docker
    commands:
      - dotnet test --no-restore --verbosity normal ./Calculator.Tests/Calculator.Tests.csproj

trigger:
  branch:
    - main
    - develop
