kind: pipeline
type: docker
name: default

steps:
  - name: restore
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet nuget locals all --clear
      - nuget restore Calculator.sln
      - dotnet restore ./Calculator/Calculator.csproj --verbosity detailed     

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet build --no-restore -c Release ./Calculator/Calculator.csproj

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - dotnet test --no-restore --verbosity normal ./Calculator.Tests/Calculator.Tests.csproj

trigger:
  branch:
    - main
    - develop
